// providers/gemini/image.js - Modified to read prompt from storage
(async (context = {}) => {
  const IMGBB_API_KEY = '869e0902a9c1bb20fd3cbab30f912c44';
  
  // Get prompt from storage (set by background)
  const { cp_gemini_prompt, cp_gemini_aspect } = await chrome.storage.local.get(['cp_gemini_prompt', 'cp_gemini_aspect']);
  await chrome.storage.local.remove(['cp_gemini_prompt', 'cp_gemini_aspect']);
  
  let prompt = cp_gemini_prompt || context.message || '';
  const aspect = cp_gemini_aspect || '1:1';
  
  if (!prompt) throw new Error('No prompt for Gemini');
  
  // Add aspect ratio instruction
  const fullPrompt = `${prompt}\n\nASPECT RATIO: ${aspect}`;
  
  // Find and interact with Gemini UI
  const editor = document.querySelector('.ql-editor') || document.querySelector('div[contenteditable="true"]');
  if (!editor) throw new Error('Gemini editor not found');
  
  editor.innerText = fullPrompt;
  editor.dispatchEvent(new Event('input', { bubbles: true }));
  
  await new Promise(r => setTimeout(r, 1000));
  
  const sendBtn = document.querySelector('mat-icon[fonticon="arrow_upward"]')?.closest('button') ||
                  document.querySelector('button[aria-label="Send message"]');
  if (!sendBtn) throw new Error('Send button not found');
  sendBtn.click();
  
  // Wait for image generation
  const beforeCount = document.querySelectorAll('img[src^="blob:"], img[src^="data:image"]').length;
  let imageUrl = null;
  
  for (let attempt = 0; attempt < 60; attempt++) {
    await new Promise(r => setTimeout(r, 2000));
    const currentCount = document.querySelectorAll('img[src^="blob:"], img[src^="data:image"]').length;
    if (currentCount > beforeCount) {
      const img = document.querySelectorAll('img[src^="blob:"], img[src^="data:image"]')[currentCount - 1];
      imageUrl = img.src;
      break;
    }
  }
  
  if (!imageUrl) throw new Error('No image generated by Gemini');
  
  // Upload to imgbb to get permanent URL
  const response = await fetch(imageUrl);
  const blob = await response.blob();
  
  const base64 = await new Promise((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result.split(',')[1]);
    reader.readAsDataURL(blob);
  });
  
  const formData = new URLSearchParams();
  formData.append('key', IMGBB_API_KEY);
  formData.append('image', base64);
  formData.append('name', `gemini_${Date.now()}.png`);
  
  const uploadRes = await fetch('https://api.imgbb.com/1/upload', { method: 'POST', body: formData });
  const uploadData = await uploadRes.json();
  
  if (!uploadData.success) throw new Error(`Upload failed: ${uploadData.error?.message}`);
  
  // Store result
  await chrome.storage.local.set({ cp_gemini_output: { imageUrl: uploadData.data.url } });
  
  return uploadData.data.url;
})();